let yosh = prompt (`yoshingizni kiriting`)
let ism = prompt (`ismingizni kiriting`)
let familiya = prompt (`familyangizni kiriting`)
let maktab = prompt (`maktabingizni kiriting`)
let manzil = prompt (`manzilingizni kiriting`)
let telnomer = prompt (`raqamingizni kiriting`)
let username = prompt (`usernameingizni kiriting`)
let natija = "Salom" + yosh + "ismim" + familiya + "familiyam" + maktab + "maktabim" + ism + "ismim" + manzil + "manzilim" + telnomer + "raqamim" + username + "nikim" 
console.log(natija)
console.log(prompt)